name: rajd
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_maps_flutter:
   git:
     url: git://github.com/flutter/plugins
     path: packages/google_maps_flutter
  #google_maps_flutter:
    #path: /Users/tobbe/git/plugins/packages/google_maps_flutter
    #path: c:/git/forks/plugins/packages/google_maps_flutter
  location: "^1.3.4"
  url_launcher: "^3.0.2"
  barcode_scan: "^0.0.4"
  font_awesome_flutter: "^7.0.0"
  mailer:
    path: c:/git/mailer
  firebase_auth: 0.5.11
  map_view: ^0.0.14
    
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/scooter2.png
     - images/scanner.png
     - images/helmet.png
     - images/iphone.png
     - images/bikeLane.png
     - images/breaks.png
     - images/user.jpg
     - images/credit.png
     
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Raleway
       fonts:
         - asset: fonts/Raleway-Bold.ttf
         - asset: fonts/Raleway-BoldItalic.ttf
         - asset: fonts/Raleway-Italic.ttf
         - asset: fonts/Raleway-Regular.ttf
           style: italic

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

